practice/auth_paractice/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

practice/auth_paractice/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_id>/comments/create', views.comment_create, name='comment_create'),
]

practice/auth_paractice/auth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

practice/auth_paractice/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

practice/auth_paractice/articles/models.py
from django.db import models
from accounts.models import User
from django.conf import Settings
from django.contrib.auth import get_user_model

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()

    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

practice/auth_paractice/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username',)


class CustomAuthenticationForm(AuthenticationForm):
    pass

practice/auth_paractice/articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        exclude = ('user',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content',)

practice/auth_paractice/accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.

def signup(request):
    if request.user.is_authenticated:
            return redirect('accounts:login')
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:signup')
    else:
        form = CustomUserCreationForm()

    context = {
        'form' : form,
    }

    return render(request, 'signup.html', context)

# def signup(request):
#     # 회원가입시 바로 로그인 창 
#     if request.user.is_authenticated:
#         return redirect('articles:index')
#     if request.method == 'POST':
#         form =CustomUserCreationForm(request.POST)
#         if form.is_valid(): # 비번 confirm까지 됐을때 / 잘못 제출시 context로 이동
#             user = form.save()
#             auth_login(request, user) # 가입시 바로 로그인
#             return redirect('articles:index')

#     if request.method =='POST':
#         if request.method == 'POST':
#             form = CustomUserCreationForm(request.POST)
#             if form.is_valid():
#                 form.save()
#                 return redirect('accounts:signup')
#     else:
#         form = CustomUserCreationForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'signup.html', context)



def login(request):
    if request.method == "POST":
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_url = request.GET.get('next') # /articles/create/

            return redirect(next_url or 'articles:index')
            # next 인자가 url에 있을 때 => '/articles/create/' or 'articles:index'
            # next 인자가 url에 없을 때 => None or 'article:index'

    else:
        form = CustomAuthenticationForm()

    context = {
        'form'  : form,
    }

    return render(request, 'login.html', context)



def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

practice/auth_paractice/articles/views.py
from django.shortcuts import render, redirect
from . models import Article
from . forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    
    articles = Article.objects.all()
    form = CommentForm()

    context = {
        'articles' : articles,
        'form' : form,
    }

    return render(request, 'index.html', context)

@login_required
def create(request):

    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:index')

    else:
        form = ArticleForm()

    context = {
        'form' : form,
    }

    return render(request, 'form.html', context)

@login_required
def comment_create(request, article_id):
    article = Article.objects.get(id=article_id)

    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.article = article
        comment.save()

        return redirect('article:index')

practice/auth_paractice/accounts/templates/account_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}


{% block body %}

{% if request.resolver_match.url_name == 'signup' %}
    <h1>회원가입</h1>

{% else %}
    <h1>로그인</h1>

{% endif %}


<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary">

</form>


{% endblock %}

practice/auth_paractice/accounts/templates/signup.html
{% extends 'base.html' %}



{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">

</form>

{% endblock %}

practice/auth_paractice/articles/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}


{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">  


</form>

{% endblock %}

practice/auth_paractice/articles/templates/index.html
{% extends 'base.html' %}
{% load bootstrap5 %}


{% block body %}

{% for article in articles %}
<div class="card" style="width: 18rem;">
    <div class="card-body">
        <h5 class="card-title">{{article.title}}</h5>
        <p class="card-text">{{article.content}}</p>
        <p class="card-text">{{article.user}}</p>
    </div>


    {% if request.user.is_authenticated %}
    <div class="card-footer">
        <form action="{% url 'articles:comment_create' article_id=article.id %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit">
        </form>
    </div>

    {% endif %}

    <div class="card-footer">
        {% for comment in article.comment_set.all %}
            <p>{{comment.user}} : {{comment.content}}</p>
        {% endfor %}
    </div>

</div>

{% endfor %}

{% endblock %}

practice/auth_paractice/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'articles:index' %}">회원 가입 & 로그인 & 로그아웃 기능 구현</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
                <a class="nav-link disabled" aria-disabled="true">유저 이름: {{user}}</a>

                {% else %}
                <a class="nav-link active" aria-current="page" href="{% url 'accounts:signup' %}">회원가입</a>
                <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>

                {% endif %}
            </div>
            </div>
        </div>
    </nav>

    <div class="container">
    {% block body %}
    {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>